[project]
name = "nlp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.5.0",
    "huggingface>=0.0.1",
    "nltk>=3.9.2",
    "numpy>=2.4.2",
    "scikit-learn>=1.8.0",
]
